kiosk-user: Added ability to update $HOME/.bashrc to automatically run 'startx'

diff --git a/packages/kiosk-user/DEBIAN/postinst b/packages/kiosk-user/DEBIAN/postinst
--- a/packages/kiosk-user/DEBIAN/postinst
+++ b/packages/kiosk-user/DEBIAN/postinst
@@ -1,5 +1,7 @@
 #!/bin/bash
-set -e
+
+# Don't exit on error
+#set -e
 
 # summary of how this script can be called:
 #       * <postinst> `configure' <most-recently-configured-version>
@@ -16,6 +18,7 @@ set -e
 
 . /usr/share/debconf/confmodule
 
+# Create systemd service to autologin kiosk user
 create_systemd_autologin() {
 	login_username="${1}"
 
@@ -59,6 +62,7 @@ EOF
 	return 0
 }
 
+# Create X11 session script for startx
 create_xsession() {
 	xsession_file="${1}/.xinitrc"
 
@@ -128,6 +132,58 @@ EOF
 	fi
 }
 
+# Update bash login file to include 'startx'
+update_startup_script_bash() {
+	login_username="${1}"
+
+	bashrc_file="/home/${login_username}/.bashrc"
+	bashrc_update=1
+
+	# Check if file has already been updated
+	if [ -f "${bashrc_file}" ]; then
+		grep startx "${bashrc_file}" >/dev/null 2>&1
+		if [ ${?} -eq 0 ]; then
+			bashrc_update=0
+		fi
+	fi
+
+	# Update bashrc
+	if [ ${bashrc_update} -eq 1 ]; then
+		echo "postinst: Updating .bashrc"
+		cat >> "${bashrc_file}" << EOF
+
+# Start X automatically
+startx
+# Exit shell so that systemd respawns automatic login
+exit
+EOF
+	fi
+}
+
+# Update the correct startup script to add startx
+update_startup_script() {
+	login_username="${1}"
+
+	user_data=$(getent passwd "${login_username}")
+	if [ ${?} -eq 0 ]; then
+		user_shell=`tmp_data=$(getent passwd "${login_username}"); basename "${tmp_data#*:/home/${login_username}:}"`
+
+		case "${user_shell}" in
+		bash)
+			update_startup_script_bash "${login_username}"
+			;;
+		*)
+			echo "postinst: unsupported shell - ${user_shell}"
+			return 255
+			;;
+		esac
+	else
+		echo "postinst: Failed to get user data"
+		return 255
+	fi
+}
+
+
 case "$1" in
 	configure)
 		if db_get kiosk-user/username; then
@@ -139,6 +195,7 @@ case "$1" in
 
 		create_systemd_autologin "${KIOSK_USER}"
 		create_xsession "/home/${KIOSK_USER}"
+		update_startup_script "${KIOSK_USER}"
 	;;
 #	abort-upgrade)
 #	;;
